export const themeOptions = [
  {
    '--bg-primary': '#181818',
    '--bg-secondary': '#282828',
    '--primary': '#1db954',
    '--text-alternate': '#666666',
    '--text-primary': '#ffffff',
    '--text-secondary': '#b3b3b3',
    name: 'Spotify',
  },
  {
    '--bg-primary': '#363b4e',
    '--bg-secondary': '#e8ac90',
    '--primary': '#d4e7c2',
    '--text-alternate': '#cd626a',
    '--text-primary': '#fffff2',
    '--text-secondary': '#363b4e',
    name: 'Autumn Flowers',
  },
  {
    '--bg-primary': '#1e352f',
    '--bg-secondary': '#335145',
    '--primary': '#828c51',
    '--text-alternate': '#a6c36f',
    '--text-primary': '#ffffff',
    '--text-secondary': '#beef9e',
    name: 'Jungle',
  },
  {
    '--bg-primary': '#00293c',
    '--bg-secondary': '#257985',
    '--primary': '#ff4447',
    '--text-alternate': '#5ea8a7',
    '--text-primary': '#ffffff',
    '--text-secondary': '#f0eff0',
    name: 'Summit',
  },
  {
    '--bg-primary': '#515365',
    '--bg-secondary': '#8badaa',
    '--primary': '#cecbb4',
    '--text-alternate': '#ffffff',
    '--text-primary': '#d27f65',
    '--text-secondary': '#5d8198',
    name: 'Seastar',
  },
  {
    '--bg-primary': '#5b6678',
    '--bg-secondary': '#7d899a',
    '--primary': '#ffb8b8',
    '--text-alternate': '#ffffff',
    '--text-primary': '#ffebd2',
    '--text-secondary': '#b5b7b4',
    name: 'Jurassic',
  },
  {
    '--bg-primary': '#634e4e',
    '--bg-secondary': '#986464',
    '--primary': '#80b5bd',
    '--text-alternate': '#ffffff',
    '--text-primary': '#eabebe',
    '--text-secondary': '#eee2e2',
    name: 'Beachfront',
  },
  {
    '--bg-primary': '#d6ae7c',
    '--bg-secondary': '#a9978b',
    '--primary': '#464776',
    '--text-alternate': '#ffffff',
    '--text-primary': '#d8dbb2',
    '--text-secondary': '#a2a5b4',
    name: 'Salamander',
  },
  {
    '--bg-primary': '#557493',
    '--bg-secondary': '#a9c391',
    '--primary': '#ffd2da',
    '--text-alternate': '#ffffff',
    '--text-primary': '#f2f2f2',
    '--text-secondary': '#eeeeee',
    name: 'Retro',
  },
];
